### ISSUE TITLE
Cmd prompt locks when user credentials are wrong with issue-uss command

### ISSUE THREAD

**Issue by ChrisAtkinson1** [ChrisPark89/zowe-cli#5]
Issuing zowe cli command where the ssh profile has invalid user or password sees the cmd prompt lock up.  
CNTL+C is needed to exit the lock.

Error looks like this.
C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli>zowe uss issue ssh  "cd /u/atkinc/small && sleepFor10Mins.sh"
Error: All configured authentication methods failed
    at doNextAuth (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2\lib\client.js:411:17)
    at tryNextAuth (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2\lib\client.js:482:5)
    at SSH2Stream.onUSERAUTH_FAILURE (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2\lib\client.js:592:5)
    at emitTwo (events.js:126:13)
    at SSH2Stream.emit (events.js:214:7)
    at parsePacket (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2-streams\lib\ssh.js:3775:10)
    at SSH2Stream._transform (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2-streams\lib\ssh.js:693:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2-streams\lib\ssh.js:252:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
Command Error:
All configured authentication methods failed
Imperative encountered an unexpected exception
Command entered: "zowe uss issue ssh cd /u/atkinc/small && sleepFor10Mins.sh"
Use "zowe uss issue --help" to view groups, commands, and options.
Error Details:
All configured authentication methods failed
Error: Timed out while waiting for handshake
    at Timeout._onTimeout (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2\lib\client.js:690:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Command Error:
Timed out while waiting for handshake
Imperative encountered an unexpected exception
Command entered: "zowe uss issue ssh cd /u/atkinc/small && sleepFor10Mins.sh"
Use "zowe uss issue --help" to view groups, commands, and options.
Error Details:
Timed out while waiting for handshake
^CTerminate batch job (Y/N)? Y

**Comment by ChrisPark89** [comment]
Fixed it on sessions branch.
