### ISSUE TITLE
zowe issue-ssh profile should have the password as optional

### ISSUE THREAD

**Issue by ChrisAtkinson1** [ChrisPark89/zowe-cli#9]
The zowe ssh.profile has

host: winmvsX.hursley.ibm.com
port: 22
user: myuser
password: myMVSpass
privateKey: myKey
keyPassword: myPass

You can use this without privateKey and keyPassword.  

However with a privateKey in use the myMVSpass password option should be optional.  The user would still be required.

**Comment by ChrisPark89** [comment]
Changed "password" as optional. The update is in the feat/pubkey branch

**Comment by ChrisAtkinson1** [comment]
Unfortunately - whilst this fix enables the creation of the profile without the users MVS password.  When attempting to use that profile....

zowe uss issue ssh "pwd" --ssh-profile sshkey
Error: All configured authentication methods failed
    at doNextAuth (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2\lib\client.js:411:17)
    at tryNextAuth (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2\lib\client.js:482:5)
    at SSH2Stream.onUSERAUTH_FAILURE (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2\lib\client.js:592:5)
    at emitTwo (events.js:126:13)
    at SSH2Stream.emit (events.js:214:7)
    at parsePacket (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2-streams\lib\ssh.js:3775:10)
    at SSH2Stream._transform (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2-streams\lib\ssh.js:693:13)
    at SSH2Stream.Transform._read (_stream_transform.js:186:10)
    at SSH2Stream._read (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2-streams\lib\ssh.js:252:15)
    at SSH2Stream.Transform._write (_stream_transform.js:174:12)
Command Error:
All configured authentication methods failed
Imperative encountered an unexpected exception
Command entered: "zowe uss issue ssh pwd --ssh-profile sshkey --sshProfile sshkey"
Use "zowe uss issue --help" to view groups, commands, and options.
Error Details:
All configured authentication methods failed
Error: Timed out while waiting for handshake
    at Timeout._onTimeout (C:\Users\CHRISTOPHERAtkinson\Documents\Zowe Stuff\ZOWE DEV\ME\zowe-cli\node_modules\ssh2\lib\client.js:690:19)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
Command Error:
Timed out while waiting for handshake
Imperative encountered an unexpected exception
Command entered: "zowe uss issue ssh pwd --ssh-profile sshkey --sshProfile sshkey"
Use "zowe uss issue --help" to view groups, commands, and options.
Error Details:
Timed out while waiting for handshake

**Comment by ChrisPark89** [comment]
Fixed both creating profile and using profile without password. the change is in sessions branch
